- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students(835542e7-b20f-4409-9ba2-d93cbdc245ad)'
    appType: 'webAppContainer'
    WebAppName: 'dockerized-app'
    deployToSlotOrASE: true
    ResourceGroupName: 'ip14aai-resource-group-1'
    SlotName: 'production'
    DockerNamespace: 'dockerized-python-app'
    DockerRepository: 'my-python-app'